# -*- coding: utf-8 -*-
"""stacks_using_arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/92-vasim/dsa-using-python/blob/main/stacks_using_arrays.ipynb
"""

L = [1,2,3,4]

L

L.append(5)

L

L.pop()

L

L[-1]

class Stack:

  def __init__(self,size):
    self.size = size
    self.__stack = [None] * self.size
    self.top = -1

  def push(self,value):

    if self.top == self.size - 1:
      return "Overflow"
    else:
      self.top+=1
      self.stack[self.top] = value

  def pop(self):

    if self.top == -1:
      return "Empty"
    else:
      data = self.stack[self.top]
      self.top-=1
      print(data)

  def traverse(self):

    for i in range(self.top + 1):
      print(self.stack[i],end=' ')

s = Stack(3)

s.stack

s.push(4)

s.push(5)

s.push(6)

s.pop()

s.pop()

s.pop()

s.pop()

s.traverse()

s.push(5)

